### ISSUE TITLE
Python 3.8 wheel linked against newer libc

### ISSUE THREAD

**Issue by LordAro** [RalfG/python-wheels-manylinux-build#14]
Got a failure with py38 (py36 & py37 are fine)

```
The wheel references external versioned symbols in these system-
provided shared libraries: libc.so.6 with versions {'GLIBC_2.4',
'GLIBC_2.2.5', 'GLIBC_2.14'}
```

I'm not sure what's happened here, somehow it's ended up linked against a newer/incorrect libc.so ?

Full results here: https://github.com/LordAro/nml/runs/553326716?check_suite_focus=true

What's gone wrong?

**Comment by RalfG** [comment]
There are some libraries used for the Python 3.8 wheel which cannot be used in the manylinux2010 specification. Auditwheel suggests to make a manylinux2014 version of the wheel. Can you try the following version of the action, with the `@v0.2.2-manylinux2014_x86_64` suffix?
```
    - name: Build manylinux Python wheels
      uses: RalfG/python-wheels-manylinux-build@v0.2.2-manylinux2014_x86_64
      with:
        python-versions: 'cp36-cp36m cp37-cp37m cp38-cp38'
        build-requirements: 'ply Pillow'  # Don't think there's another way of passing these in
      if: startsWith(matrix.os, 'ubuntu')
```
