### ISSUE TITLE
How do you build packages for things such as i686 and aarch64?

### ISSUE THREAD

**Issue by kesmit13** [RalfG/python-wheels-manylinux-build#60]
I'm using your action to build x86 packages, but I'm not sure how to build them for alternate architectures. Your documentation mentions using alternate docker images, but I'm not sure how to create that architecture in Github actions. Do you have any examples of that?

**Comment by mrmundt** [comment]
@kesmit13 - I have an example [here](https://github.com/Pyomo/pyomo/blob/4cc82748ab975b734d47debc52e7ea71d5c33ba0/.github/workflows/release_wheel_creation.yml#L61) for which we used the [docker/QEMU](https://github.com/marketplace/actions/docker-setup-qemu) action to simulate the architecture.

**Comment by RalfG** [comment]
Indeed, first add an action to setup Docker emulation: 

```
    - uses: docker/setup-qemu-action@v1
      name: Set up QEMU
```

Then use this action with the specific container for the architecture you require, e.g.:

```
    - name: Build manylinux Python wheels
      uses: RalfG/python-wheels-manylinux-build@v0.4.0-manylinux2014_aarch64
      with:
        python-versions: ${{ matrix. Wheel-version }}
```

For more complex setups, you can also use the official [PyPA/cibuildwheel](https://github.com/pypa/cibuildwheel) action.
